os: linux
dist: xenial
language: java
jdk:
  - openjdk11
  - openjdk8

env:
  global:
    - PACKAGE_BUILD_IMAGE=sorintdev/rpmbuild-centos7
    - WORKSPACE='/project'
    - DIST=rhel7 

service:
  - docker

sudo: required
 
before_install:
  - sudo docker pull ${PACKAGE_BUILD_IMAGE}
  - export VERSION=`cat pom.xml | grep "version" | cut -d'>' -f2 | cut -d'<' -f1 | head -n 2 | tail -n 1`
install:
  - sudo docker run -d --rm -it -e WORKSPACE="${WORKSPACE}" -e TRAVIS_REPO_SLUG="${TRAVIS_REPO_SLUG}" -e TRAVIS_BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}" -v $PWD:"${WORKSPACE}" --name package_builder ${PACKAGE_BUILD_IMAGE} /bin/cat

script:
  - mvn -q package
  - sed -i "s|ERCOLE_VERSION|${VERSION}|g" package/rhel7/ercole-server.spec
  - docker exec -it package_builder /bin/sh -c "mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}"
  - docker exec -it package_builder /bin/sh -c "ln -s ${WORKSPACE} ~/rpmbuild/SOURCES/ercole-server.${VERSION}.tar.gz"
  - docker exec -it package_builder /bin/sh -c "cd ${WORKSPACE} && rpmbuild -bb package/${DIST}/ercole-server.spec"
  - docker exec -it package_builder /bin/sh -c "cd ${WORKSPACE} && cp ~/rpmbuild/RPMS/x86_64/ercole-server-${VERSION}-1.el*.x86_64.rpm target/"
after_failure:
  - find .

deploy:
  provider: releases
  api_key:
    secure: TEKRCDsimuos3apXsoqWmBeDFFDnsxDA/5EnaTMeTn6nzw388YznJ3hpM5BSShX1zH5Es5GP48GHxtnsppSMlVsVJ+mO152XzR/23aWZWKJ3OPYpIXi4l7sGlcyNyOFja9GiVEZGNM2T9RL9EgAsWmvjLMIoV3BoEtbvxhhtw3/FvpOC9jsaAQKGZShJYdImAEsQGz3yGKrTcS/vp6+kCyj8twLJsAXtwzU53NzZgFaBvyUJizZHUfCPrb7paxy9LI3U9+VfC7c1vtD7wQV1YAU/DLpxz7Bs4vROlbcJgvBPnfUmluiAMEfqIecTx86KbGcT8qdTVgIVyEvqL7TT66RloT2R3B59cvflgo8QxFAveVTcMVDpZjIyab/9rtOHwxE4yJpAxwooCKYoy9IapWXVVtFqv0CS/aYl2U32qF8rcSM9EAozeyFxP+deMRSF8Iq3h3JfEQldGFquTEbvZAIopVb8XNdiRxBen0rC3d+QhkrnNTVcCtbaGhyuRZ1FGWy7vIMMj5cy+pq5vLs27wGmYQYFvfr8eIOcxcZFg24eHSCxfyMiH9O/ToCxrjo1pvSf3UbI+AZDg1q+rNOqufK//T7pxZopj4jBKSzm5VCpW8Bm7O8KPEJquHiivZpw4ivBUK/BSg0UYWFsfCW8Bw7J1dvKrDCa+DP1zjzr+YM=
  file_glob: true
  file: target/ercole-server-*.*
  skip_cleanup: true
  on:
    repo: amreo/ercole-server
    jdk: openjdk11
