os: linux
dist: xenial
language: java
jdk:
  - openjdk11
  - openjdk8

env:
  global:
    - PACKAGE_BUILD_IMAGE=sorintdev/rpmbuild-centos7
    - WORKSPACE='/project'
    - DIST=rhel7 

service:
  - docker

sudo: required
 
before_install:
  - sudo docker pull ${PACKAGE_BUILD_IMAGE}
  - if [ -z ${TRAVIS_TAG} ] || [ ${TRAVIS_TAG} == *-* ]; then export VERSION=latest; else export VERSION=${TRAVIS_TAG}; fi
  - echo ${TRAVIS_TAG}
  - echo ${VERSION}

install:
  - sudo docker run -d --rm -it -e WORKSPACE="${WORKSPACE}" -e TRAVIS_REPO_SLUG="${TRAVIS_REPO_SLUG}" -e TRAVIS_BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}" -v $PWD:"${WORKSPACE}" --name package_builder ${PACKAGE_BUILD_IMAGE} /bin/cat


script:
  - mvn -q package
  - sed -i "s|ERCOLE_VERSION|${VERSION}|g" package/rhel7/ercole-agent.spec
  - docker exec -it package_builder /bin/sh -c "cd ${WORKSPACE} && rpmbuild --quiet -bl package/${DIST}/ercole-server.spec" || echo rpmbuild
  - docker exec -it package_builder /bin/sh -c "mkdir ~/rpmbuild/SOURCES/ercole-server-${VERSION}"
  - docker exec -it package_builder /bin/sh -c "cd ${WORKSPACE} && cp -r * ~/rpmbuild/SOURCES/ercole-server-${VERSION}/"
  - docker exec -it package_builder /bin/sh -c "cd ${WORKSPACE} && tar -C ~/rpmbuild/SOURCES -cvzf ~/rpmbuild/SOURCES/ercole-server-${VERSION}.tar.gz ercole-server-${VERSION}"
  - docker exec -it package_builder /bin/sh -c "cd ${WORKSPACE} && rpmbuild -bb package/${DIST}/ercole-server.spec"
  - docker exec -it package_builder /bin/sh -c "find ~/rpmbuild/"
  - docker exec -it package_builder /bin/sh -c "cd ${WORKSPACE} && cp ~/rpmbuild/RPMS/x86_64/ercole-server-${VERSION}-1.el*.x86_64.rpm targer/"
after_failure:
  - find .

deploy:
  provider: releases
  api_key:
    secure: TEKRCDsimuos3apXsoqWmBeDFFDnsxDA/5EnaTMeTn6nzw388YznJ3hpM5BSShX1zH5Es5GP48GHxtnsppSMlVsVJ+mO152XzR/23aWZWKJ3OPYpIXi4l7sGlcyNyOFja9GiVEZGNM2T9RL9EgAsWmvjLMIoV3BoEtbvxhhtw3/FvpOC9jsaAQKGZShJYdImAEsQGz3yGKrTcS/vp6+kCyj8twLJsAXtwzU53NzZgFaBvyUJizZHUfCPrb7paxy9LI3U9+VfC7c1vtD7wQV1YAU/DLpxz7Bs4vROlbcJgvBPnfUmluiAMEfqIecTx86KbGcT8qdTVgIVyEvqL7TT66RloT2R3B59cvflgo8QxFAveVTcMVDpZjIyab/9rtOHwxE4yJpAxwooCKYoy9IapWXVVtFqv0CS/aYl2U32qF8rcSM9EAozeyFxP+deMRSF8Iq3h3JfEQldGFquTEbvZAIopVb8XNdiRxBen0rC3d+QhkrnNTVcCtbaGhyuRZ1FGWy7vIMMj5cy+pq5vLs27wGmYQYFvfr8eIOcxcZFg24eHSCxfyMiH9O/ToCxrjo1pvSf3UbI+AZDg1q+rNOqufK//T7pxZopj4jBKSzm5VCpW8Bm7O8KPEJquHiivZpw4ivBUK/BSg0UYWFsfCW8Bw7J1dvKrDCa+DP1zjzr+YM=
  file_glob: true
  file: target/ercole-server-*.*
  skip_cleanup: true
  on:
    repo: amreo/ercole-server
    jdk: openjdk11